const languages = {
  "1c": "1C",
  "4d": "4D",
  abnf: "ABNF",
  accesslog: "Access logs",
  ada: "Ada",
  arduino: "Arduino (C++ w/Arduino libs)",
  armasm: "ARM assembler",
  avrasm: "AVR assembler",
  actionscript: "ActionScript",
  alan: "Alan IF",
  ln: "Alan",
  angelscript: "AngelScript",
  apache: "Apache",
  applescript: "AppleScript",
  arcade: "Arcade",
  asciidoc: "AsciiDoc",
  aspectj: "AspectJ",
  autohotkey: "AutoHotkey",
  autoit: "AutoIt",
  awk: "Awk",
  axapta: "X++",
  bash: "Bash",
  basic: "Basic",
  bbcode: "BBCode",
  blade: "Blade (Laravel)",
  bnf: "BNF",
  brainfuck: "Brainfuck",
  csharp: "C#",
  c: "C",
  cpp: "C++",
  cal: "C/AL",
  cos: "Cache Object Script",
  cmake: "CMake",
  coq: "Coq",
  csp: "CSP",
  css: "CSS",
  capnproto: "Cap’n Proto",
  chaos: "Chaos",
  chapel: "Chapel",
  cisco: "Cisco CLI",
  clojure: "Clojure",
  coffeescript: "CoffeeScript",
  cpc: "CpcdosC+",
  crmsh: "Crmsh",
  crystal: "Crystal",
  cypher: "Cypher (Neo4j)",
  d: "D",
  dns: "DNS Zone file",
  dos: "DOS",
  dart: "Dart",
  delphi: "Delphi",
  diff: "Diff",
  django: "Django",
  dockerfile: "Dockerfile",
  dsconfig: "dsconfig",
  dts: "DTS (Device Tree)",
  dust: "Dust",
  dylan: "Dylan",
  ebnf: "EBNF",
  elixir: "Elixir",
  elm: "Elm",
  erlang: "Erlang",
  excel: "Excel",
  extempore: "Extempore",
  fsharp: "F#",
  fix: "FIX",
  fortran: "Fortran",
  gcode: "G-Code",
  gams: "Gams",
  gauss: "GAUSS",
  godot: "GDScript",
  gherkin: "Gherkin",
  hbs: "Glimmer and EmberJS",
  gn: "GN for Ninja",
  go: "Go",
  gf: "Grammatical Framework",
  golo: "Golo",
  gradle: "Gradle",
  groovy: "Groovy",
  html: "HTML",
  xml: "XML",
  http: "HTTP",
  haml: "Haml",
  handlebars: "Handlebars",
  haskell: "Haskell",
  haxe: "Haxe",
  hlsl: "High-level shader language",
  hy: "Hy",
  ini: "INI",
  toml: "TOML",
  inform7: "Inform7",
  irpf90: "IRPF90",
  json: "JSON",
  java: "Java",
  javascript: "JavaScript",
  jolie: "Jolie",
  julia: "Julia",
  kotlin: "Kotlin",
  tex: "LaTeX",
  leaf: "Leaf",
  lean: "Lean",
  lasso: "Lasso",
  less: "Less",
  ldif: "LDIF",
  lisp: "Lisp",
  livecodeserver: "LiveCode Server",
  livescript: "LiveScript",
  lua: "Lua",
  makefile: "Makefile",
  markdown: "Markdown",
  mathematica: "Mathematica",
  matlab: "Matlab",
  maxima: "Maxima",
  mel: "Maya Embedded Language",
  mercury: "Mercury",
  mirc: "mIRC Scripting Language",
  mizar: "Mizar",
  mojolicious: "Mojolicious",
  monkey: "Monkey",
  moonscript: "Moonscript",
  n1ql: "N1QL",
  nsis: "NSIS",
  never: "Never",
  nginx: "Nginx",
  nim: "Nim",
  nix: "Nix",
  ocl: "Object Constraint Language",
  ocaml: "OCaml",
  objectivec: "Objective C",
  glsl: "OpenGL Shading Language",
  openscad: "OpenSCAD",
  ruleslanguage: "Oracle Rules Language",
  oxygene: "Oxygene",
  pf: "PF",
  php: "PHP",
  papyrus: "Papyrus",
  parser3: "Parser3",
  perl: "Perl",
  plaintext: "Plaintext",
  pony: "Pony",
  pgsql: "PostgreSQL & PL/pgSQL",
  powershell: "PowerShell",
  processing: "Processing",
  prolog: "Prolog",
  properties: "Properties",
  protobuf: "Protocol Buffers",
  puppet: "Puppet",
  python: "Python",
  profile: "Python profiler results",
  "python-repl": "Python REPL",
  qsharp: "Q#",
  k: "Q",
  qml: "QML",
  r: "R",
  cshtml: "Razor CSHTML",
  reasonml: "ReasonML",
  redbol: "Rebol & Red",
  rib: "RenderMan RIB",
  rsl: "RenderMan RSL",
  risc: "RiScript",
  graph: "Roboconf",
  robot: "Robot Framework",
  "rpm-specfile": "RPM spec files",
  ruby: "Ruby",
  rust: "Rust",
  SAS: "SAS",
  scss: "SCSS",
  sql: "SQL",
  p21: "STEP Part 21",
  scala: "Scala",
  scheme: "Scheme",
  scilab: "Scilab",
  shexc: "Shape Expressions",
  shell: "Shell",
  smali: "Smali",
  smalltalk: "Smalltalk",
  sml: "SML",
  solidity: "Solidity",
  spl: "Splunk SPL",
  stan: "Stan",
  stata: "Stata",
  iecst: "Structured Text",
  stylus: "Stylus",
  subunit: "SubUnit",
  supercollider: "Supercollider",
  svelte: "Svelte",
  swift: "Swift",
  tcl: "Tcl",
  terraform: "Terraform (HCL)",
  tap: "Test Anything Protocol",
  thrift: "Thrift",
  tp: "TP",
  tsql: "Transact-SQL",
  twig: "Twig",
  typescript: "TypeScript",
  "unicorn-rails-log": "Unicorn Rails log",
  vbnet: "VB.Net",
  vba: "VBA",
  vbscript: "VBScript",
  vhdl: "VHDL",
  vala: "Vala",
  verilog: "Verilog",
  vim: "Vim Script",
  x86asm: "x86 Assembly",
  xl: "XL",
  xquery: "XQuery",
  yml: "YAML",
  zenscript: "ZenScript",
  zephir: "Zephir",
};

export default function Languages({ ...props }) {
  return (
    <select id="syntax" {...props} defaultValue="plaintext">
      {Object.entries(languages).map(([key, value]) => (
        <option value={key}>{value}</option>
      ))}
    </select>
  );
}
